owner: renggli
repo: upptime

sites:
  - name: Lukas Renggli
    url: https://www.lukas-renggli.ch
    icon: https://www.lukas-renggli.ch/favicon.ico
  - name: TextLint
    url: https://textlint.lukas-renggli.ch
    icon: https://textlint.lukas-renggli.ch/favicon.ico
  - name: Smalltalk Code
    url: https://source.lukas-renggli.ch
    icon: https://source.lukas-renggli.ch/favicon.ico

assignees:
  - renggli

status-website:
  baseUrl: /upptime
  name: "Lukas Renggli: Status Website"
